// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
// Import the generated file
import 'firebase_options.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYvofUqUQx8c6G5WDL6DXj392k2NBjWqo',
    appId: '1:1032679004655:web:39cbe2142fcfd1a101fe1a',
    messagingSenderId: '1032679004655',
    projectId: 'waelfirebase-d799b',
    authDomain: 'waelfirebase-d799b.firebaseapp.com',
    storageBucket: 'waelfirebase-d799b.appspot.com',
    measurementId: 'G-J0673TFFJD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT8X5kha5O7GhbeLvDAK7EAD1K2hKjieQ',
    appId: '1:1032679004655:android:43cc5b52c520fa6c01fe1a',
    messagingSenderId: '1032679004655',
    projectId: 'waelfirebase-d799b',
    storageBucket: 'waelfirebase-d799b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoDsUHtt3KxIA084-rqRNDvcC84d3I4ho',
    appId: '1:1032679004655:ios:abc8b7bf4494789a01fe1a',
    messagingSenderId: '1032679004655',
    projectId: 'waelfirebase-d799b',
    storageBucket: 'waelfirebase-d799b.appspot.com',
    iosBundleId: 'com.example.waelfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoDsUHtt3KxIA084-rqRNDvcC84d3I4ho',
    appId: '1:1032679004655:ios:abc8b7bf4494789a01fe1a',
    messagingSenderId: '1032679004655',
    projectId: 'waelfirebase-d799b',
    storageBucket: 'waelfirebase-d799b.appspot.com',
    iosBundleId: 'com.example.waelfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYvofUqUQx8c6G5WDL6DXj392k2NBjWqo',
    appId: '1:1032679004655:web:a2d6927a2151c5b101fe1a',
    messagingSenderId: '1032679004655',
    projectId: 'waelfirebase-d799b',
    authDomain: 'waelfirebase-d799b.firebaseapp.com',
    storageBucket: 'waelfirebase-d799b.appspot.com',
    measurementId: 'G-RFGYGMC8Z2',
  );
}
